name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🔥 Breaking Changes'
    labels:
      - 'breaking'
      - 'break'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'hotfix'
      - 'bugfix'
      - 'bug'
  - title: '👋 Deprecated'
    labels:
      - 'deprecation'
  - title: '🔗 Dependency Updates'
    labels:
      - 'library-update'
      - 'dependencies'
  - title: '🛠  Internal Updates'
    labels:
      - 'update'
      - 'internal'
  - title: '📚 Docs'
    labels:
      - 'doc'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'feature'
    title:
      - '/feature/i'
      - '/feat/i'
  - label: 'documentation'
    files:
      - '*.md'
    title:
      - '/doc/i'
      - '/documentation/i'
  - label: 'bug'
    title:
      - '/fix/i'
      - '/hotfix/i'
      - '/bug/i'
      - '/bugfix/i'
  - label: 'update'
    title:
      - '/internal/i'
      - '/update/i'
  - label: 'deprecation'
    title:
      - '/deprecate/i'

